### ISSUE TITLE
Train gui glitch

### ISSUE THREAD

**Issue by pla** [raiguard/TrainGroups#11]
### Description

With Train Groups mod installed the locomotive gui has a glitch on the bottom that overlaps some button in schedule when the schedule is longer. It happens on every save I have. Testet it with vanilla 1.1.76, flib 0.12..4 and Train Groups 1.3.3 on windows 10

### Reproduction

![train-groups](https://user-images.githubusercontent.com/373679/221133340-41e0958f-5966-49bd-87d7-db7ff2fdfd9c.png)

**Comment by raiguard** [comment]
Thanks for the report. This is actually a bug in the base game, and has been fixed for the next version of the game.
