### ISSUE TITLE
Feature request: also synchronize the train colors

### ISSUE THREAD

**Issue by slikts** [raiguard/TrainGroups#12]

**Comment by raiguard** [comment]
I considered adding this when I first made the mod, but it's too complex and would have too many edge-cases with different train compositions. I recommend trying the Automatic Train Painter mod.

**Comment by slikts** [comment]
Automatic Train Painter unfortunately [isn't currently compatible with multiplayer](https://mods.factorio.com/mod/Automatic_Train_Painter/discussion/62c742796a21326586abe440).

**Comment by raiguard** [comment]
Would you be satisfied with single colors only? The main issues come up with multiple colors of train, but if all locomotives were the same color might be possible.
