### ISSUE TITLE
Feature request: assign new trains to group with same schedule

### ISSUE THREAD

**Issue by mpcomplete** [raiguard/TrainGroups#13]
Often I want to bulk add trains with the same schedule. It would be nice if, like the feature that auto-creates groups for trains with the same schedule, there was a way to bulk-assign these new trains to the existing group with that same schedule. Either automatically, or with a button that bulk assigns all trains with a schedule to a specified group.

**Comment by raiguard** [comment]
There is a button to create groups based on schedule when you don't have any groups in the overview GUI, but that functionality is not available when there are already existing groups. I will look into making it usable at any time.

**Comment by raiguard** [comment]
So, reading this again, I'm not sure exactly what you're looking for. You can get this already by using shift right-click and shift left-click to copy/paste the schedules, which also copy/pastes the group. You can set the group on one of the trains, then copy/paste it to the others.

**Comment by mpcomplete** [comment]
You are right, this is a minor convenience feature for a fairly niche scenario: where you have several existing trains in the network with the same schedule. For new trains you can copy/paste them into groups. I simply forgot to do this for a handful of trains and then had to track them down, which is annoying when you have dozens of trains with the same schedule.
