### ISSUE TITLE
UI windows gone since update

### ISSUE THREAD

**Issue by compilenix** [raiguard/TrainGroups#17]
### Description

The "Groups" window in the "Trains overview" and the "change train group" in the "Locomotive" window are no longer shown since I've update from 1.3.3 to 1.3.5. But the background stuff still works, i.e. if I change the schedule of a train, all other trains from that group get the change too.

Factorio version: 1.1.80 build 60618 linux64

Downgrading to 1.3.3 does resolve the issue.

If you can't reproduce the issue, I can provide my currently affected save game and mods (about 140 MiB in total).

Thanks for this really useful mod and greetings 😊

### Reproduction

1. Update from mod version 1.3.3 to 1.3.5

**Comment by compilenix** [comment]
If I reload the game I can see and interact with both UI's but after a couple of times the UI's stop being displayed again, until 1-3 save game reloads

**Comment by raiguard** [comment]
I can't reproduce, could you please send me your save file?

**Comment by raiguard** [comment]
At the very least, please send me your log file so I can sync with your active mods.

**Comment by compilenix** [comment]
Hey, sorry for the late reply.

I just was able to test a this a little further, because I've notices that this does only occurs during multiplayer sessions. To be more specific on those with a rather slow or bad internet connection (80 game ticks latency and above and sustained >3% packet loss).

Since this is possibly related to the core application network protocol stack, just a bad connection and difficult to reproduce in nature, you might just want to close this issue.

Greetings :)
