### ISSUE TITLE
Game freezes when adding a temp stop with no schedule.

### ISSUE THREAD

**Issue by BlackAsLight** [raiguard/TrainGroups#18]
### Description

v1.3.4 did not seem to fix the bug about adding temp stops with no schedule. My game becomes unresponsive when the train hits that stop.

### Reproduction

1. Load Save: [Train Group Mod Test.zip](https://github.com/raiguard/TrainGroups/files/11395561/Train.Group.Mod.Test.zip)
2. Add a temp stop and remove its schedule
3. Watch it freeze the game.

**Comment by raiguard** [comment]
Congratulations, you have discovered a bug in the game engine!!! I have added this to my todo list and will take a look when I can. Thanks for the report!
