### ISSUE TITLE
Schedule isn't being rememebred for refuel station

### ISSUE THREAD

**Issue by BlackAsLight** [raiguard/TrainGroups#19]
### Description

The schedule for station with the refuel icon in it isn't being applied to other trains in that same group. I am having to manually go into every train and tell them all to wait 5 seconds of inactivity before leaving the refuel station.

**Comment by raiguard** [comment]
This actually isn't a bug. Train Schedule Signals uses the refuel icon from TCS, so if you name a station using that icon, those wait conditions are controlled by train schedule signals. Train groups intentionally doesn't sync stations controlled by TSS because TSS will do it for you.

**Comment by BlackAsLight** [comment]
I saw that the station listed in the train was disabled for some so it would jump over it, but without a wait condition I observe the train just flying pass the station and not stopping to get fuel. Is it meant to apply its own wait condition as well? It is the wait conditions that aren’t being synced while the schedule to go to that station does indeed appear in all trains. Talking to some other people, I think I may have communicated that badly in the original post.

**Comment by raiguard** [comment]
The wait conditions are controlled by train schedule signals. If you want to use the refuel station normally, then you need to remove that mod.

**Comment by raiguard** [comment]
I recommend reading the tips & tricks entries for trains schedule signals. Honestly, I don't think that that mod is really necessary with train groups, and it just makes stations more difficult to configure.

**Comment by BlackAsLight** [comment]
I wasn't using the icons from Train Schedule Signals when I created this issue. I was only using the refuel icon from Train Control Signals. I understand that the Train Schedule Signals in a train name will cause it to control the wait conditions of that station, but besides that mod being installed, it played no relevance in the issue, so from my understanding TrainGroup should have been syncing my wait condition.
